input {
  file {
    path => "/logs/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

filter {
  # Puedes aplicar filtros aquí si necesitas procesar los logs antes de enviarlos a Elasticsearch.
}

output {
  elasticsearch {
    hosts => ["https://161.132.48.111:9200"]  # Ajusta esto a la URL de tu instancia de Elasticsearch
    user => "${ELASTICSEARCH_USERNAME}"  # Ajusta esto a tu usuario de Elasticsearch
    password => "${ELASTICSEARCH_PASSWORD}"  # Ajusta esto a tu contraseña de Elasticsearch
    ssl => true
    ssl_certificate_verification => false
    index => "${PROJECT_NAME}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }  # Esto es útil para depuración
}